# Tabla Y4-125

Extraer datos

In [2]:
import os
#from specdal import Collection, Spectrum, read
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

datadir = "./Espectros_FORS_2/Y4"
archivos = list()
etiquetas = ['A1','A2','A3','A4','A5',
             'B1','B2','B3','B4','B5',
             'C1','C2','C3','C4','C5',
             'D1','D2','D3','D4','D5',
             'E1','E2','E3','E4','E5',
            ]

for f in os.listdir(datadir):
    title =str(f)[8:-8]
    archivos.append(f)
archivos.sort()

In [3]:
specs = list()
specs_df = list()
features = []

def dar_intervalo(inicio,fin):
    return [inicio-350,fin-350]
interval=dar_intervalo(500,600)

ini=interval[0]
fin=interval[1]

In [4]:
for f in archivos:
    data = pd.read_csv(datadir+"/"+f,delimiter='\t')
    title =str(f)[:-4]
    dev_x = data['Wavelength'][ini:fin]
    dev_y = data[title][ini:fin]
    df = pd.DataFrame({'x': dev_x, 'y': dev_y})
    specs_df.append(df)
    tmp_arr = df.to_numpy()
    specs.append(tmp_arr)

    tmp = np.array(dev_y)
    features.append(tmp)
print(len(specs))
print(len(specs_df))
len(features)

125
125


125

In [5]:
#feature_names = data['feature_names']
feature_names = ['wavelength','reflectance']

#labels = np.concatenate((lista, lista))
#features=np.concatenate((features, features))
indexes = dev_x
labels = [i for i in range(25) for _ in range(5)]
print(len(labels))
print(len(features))

125
125


# Bayes ingenuo

In [6]:
train, test, train_labels, test_labels = train_test_split(
   features,labels,test_size = 1, random_state = 22
)

#print(train)
#print(test)
#print(train_labels)
#print(test_labels)


GNBclf = GaussianNB()

model = GNBclf.fit(train, train_labels)
print(len(model.classes_))
test=features[:125]
preds = GNBclf.predict(test)
print(preds)
print(GNBclf.score(test,labels))

25
[ 0  0  0  0  0  1  1  1  1  1  2  2  2  2  2  3  3  3  3  3  4  4  4  4
  4  5  5  5  5  5  6  6  6  6 13  7  7  7  7  7  8  8  8  8  8  9 23  9
  9 23 10 10 10 10 10 11 11 11 11 11 12 12 12 12 12 13 13  9 13 13 14 14
 14 14 14 15 15 15 15 15 16 16 16 16 16 17 17 17 17 17 18 18 18 18 18 19
 19 19 19 19 20 20 20 20 20 21 21 21 21 21 22 22 22 22 22 23 23 23  9  9
 24 24 24 19 24]
0.944


In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(preds, labels)

0.944

# Linear regression

In [8]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train, train_labels)
pb = reg.predict(test)
print(reg.score(train, train_labels))

len(pb)
for i in range(len(pb)):
    print("Predicción en",i," es ",round(pb[i],2))

0.9614603489122188
Predicción en 0  es  0.24
Predicción en 1  es  0.49
Predicción en 2  es  -3.05
Predicción en 3  es  2.96
Predicción en 4  es  -3.33
Predicción en 5  es  3.48
Predicción en 6  es  0.63
Predicción en 7  es  1.0
Predicción en 8  es  1.03
Predicción en 9  es  -0.46
Predicción en 10  es  -0.19
Predicción en 11  es  2.06
Predicción en 12  es  1.59
Predicción en 13  es  2.2
Predicción en 14  es  3.27
Predicción en 15  es  2.77
Predicción en 16  es  3.84
Predicción en 17  es  2.28
Predicción en 18  es  2.99
Predicción en 19  es  4.66
Predicción en 20  es  5.81
Predicción en 21  es  3.1
Predicción en 22  es  2.02
Predicción en 23  es  3.5
Predicción en 24  es  7.48
Predicción en 25  es  5.43
Predicción en 26  es  5.44
Predicción en 27  es  6.99
Predicción en 28  es  4.47
Predicción en 29  es  5.9
Predicción en 30  es  7.13
Predicción en 31  es  8.18
Predicción en 32  es  8.21
Predicción en 33  es  9.12
Predicción en 34  es  7.58
Predicción en 35  es  8.21
Predicción en 36  es

# Logistic Regression

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

clf = LogisticRegression(penalty='l2',solver='lbfgs', max_iter=4000)
#make_pipeline(StandardScaler(), LogisticRegression())
clf.fit(train, train_labels)
print(clf.score(train, train_labels))
print(clf.predict_proba(test))
print(clf.predict(test))

0.45161290322580644
[[0.0806953  0.04497302 0.01323616 ... 0.03765719 0.02377264 0.02800056]
 [0.07974637 0.04190547 0.01181758 ... 0.03844259 0.02499869 0.02912443]
 [0.08131458 0.04450456 0.01307234 ... 0.03756243 0.0237644  0.02795964]
 ...
 [0.02883231 0.00983711 0.00115172 ... 0.04878039 0.05595248 0.05373038]
 [0.02800786 0.00909479 0.00102804 ... 0.0486101  0.05712891 0.05436614]
 [0.02878416 0.00976909 0.00114028 ... 0.04876657 0.05605628 0.05378482]]
[ 0  0  0  0  0  2  1  1  1  1  2  2  2  2  2  3 12  3  3  3  4  1  4  1
  1  5  7  5  5  5 23 23 23 23 23 10  0  0  0  0 15  8 11 11 11 23 23 23
 23 23 10 10 10 10 10 15 15 11 15 11 12 12 12 12 12 23 23 23 23 23 23 23
 23 23 23 15 15  9 15 15 23 23 23 23 23 23 23 23 16 16 18 18 18 18 18 23
 23 23 23 23 23 16 18 17 17 21 21 21 21 21 16 23 17 17 17 23 23 23 23 23
 23 23 23 23 23]


# Perceptron

In [11]:
from sklearn.datasets import load_digits
from sklearn.linear_model import Perceptron
clf = Perceptron(tol=1e-3, random_state=0)
clf.fit(train, train_labels)
Perceptron()
preds=clf.predict(train)
print(clf.score(train, train_labels))


0.13709677419354838


# K-Nearest Neighbours


In [ ]:
size=len(indexes)
nlabels= list()
for e in etiquetas:
    er = [e for _ in range(5)]
    nlabels+=er

In [ ]:
i=0
# Concatenate Target values
for _ in range(125):
    tmp_class = [nlabels[i] for _ in range(size)]
    array_tmp = np.stack([indexes,features[i],tmp_class], axis=1)
    if i==0:
        y = np.array(array_tmp)
    else:
        y = np.concatenate((y,array_tmp))
    i+=1
np.array(y).shape
y

In [ ]:
# X Training data
for i in range(125):
    t = [2 for _ in range(size)]
    array_tmp = np.stack([features[i],t], axis=1)
    if i==0:
        X = np.array(array_tmp)
    else:
        X = np.concatenate((X,array_tmp))
np.array(X).shape
X

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classes = nlabels
neigh = KNeighborsClassifier()
neigh.classes_ = classes
neigh.n_features_in_=2
neigh.n_jobs=3

neigh.fit(X,y)

In [ ]:
def predecir(spec):
    t = [2 for _ in range(size)]
    array_X = np.stack([spec,t], axis=1)
    #array_X = i
    prediccion=neigh.predict(array_X)
    print("Prediccion=")
    print(prediccion)
    frec = {'A1':0,'A2':0,'A3':0,'A4':0,'A5':0,
                'B1':0,'B2':0,'B3':0,'B4':0,'B5':0,
                'C1':0,'C2':0,'C3':0,'C4':0,'C5':0,
                'D1':0,'D2':0,'D3':0,'D4':0,'D5':0,
                'E1':0,'E2':0,'E3':0,'E4':0,'E5':0,}
    for ren in prediccion:
        elem=ren[2]
        if elem in frec:
            frec[elem] +=1

    print("Probabilidad por clase: ")
    print(neigh.predict_proba(array_X))
    return frec

spec=features[0]
predi=predecir(spec)

In [ ]:
sum=0
for p in predi:
    ratio = predi[p]/size
    sum+=ratio
    print(p," :",(ratio*100))
sum

# Probar con datos desconocidos